### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gittyhubbyfrankybobby** [MSISAC/STIX-TAXII-Integration#1]
Linux ubuntu1 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

python --version
Python 2.7.15rc1

I ran the api2cisco.py unmodified.
After inputing all the inputs I get the following error:

Traceback (most recent call last):
  File "api2cisco.py", line 202, in <module>
    output,first,lastAddr,oldAddrs = verifyOutFile(outputLocation,outputFile)
  File "api2cisco.py", line 73, in verifyOutFile
    lastAddr = oldAddrs[-1]
IndexError: list index out of range

**Comment by gittyhubbyfrankybobby** [comment]
Seems I get the out of range because the csv file is empty? Odd because the Api2Snort.py creates the rules files without issue.

**Comment by rbrowndev** [comment]
I was able to replicate the error on my box. I just merged a fix that will hopefully solve this issue.
